### system defaults
#set -o vi

export EDITOR='vi'
export VISUAL='vi'

export PAGER='less'
export LESS='-isMR --shift 5'
eval "$(lesspipe.sh)"

### auto completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

bind 'set completion-ignore-case on'
bind 'set completion-map-case on'
bind 'set show-all-if-ambiguous on'

### aliases
alias    ..='cd ..'
alias   ...='cd ../..'
alias  ....='cd ../../..'
alias  -- -='cd -'

alias    ls='ls -G'
alias     l='ls -lh'
alias    lt='l -tr'
alias    la='l -A'
alias   lat='la -tr'

alias  grep='grep --color=auto'
alias fgrep='grep --color=auto'
alias egrep='grep --color=auto'

alias refresh='source ~/.bashrc'

### theme
export PROMPT_COMMAND=__prompt_command

function __prompt_command() {
  local EXIT="$?"

  local   PURPLE="\[\033[0;35m\]"
  local    GREEN="\[\033[0;32m\]"
  local      RED="\[\033[0;31m\]"
  local NO_COLOR="\[\033[0m\]"

  PS1=""
  PS1+="$GREEN\w"
  PS1+="$PURPLE$(__git_ps1) "
  if [ $EXIT != 0 ]; then
    PS1+="$RED"
  else
    PS1+="$NO_COLOR"
  fi
  PS1+="\$ $NO_COLOR"
}

### history
shopt -s histappend
shopt -s cmdhist
export HISTCONTROL=erasedups:ignoreboth
export HISTSIZE=500000
export HISTFILESIZE=100000
export PROMPT_COMMAND="$PROMPT_COMMAND; history -a"
export HISTIGNORE="&:[ ]*:exit:ls:l:lt:la:lat:bg:fg:history"
export HISTFORMAT='%F %T '

### functions
# creates the directory and changes into it
mkcd() { [[ -n "$1" ]] && mkdir -p $1 && cd $1; }
# list current processes for given pattern
fps() { ps ax | grep -i "${1:-""}" | grep -v grep; }
# don't forget the : when using scp
scp(){ [[ "$@" =~ : ]] && command scp "$@" || echo 'You forgot the colon!'; }

### navigation
shopt -s autocd
shopt -s dirspell
shopt -s cdspell

### git
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="verbose"

### ruby
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

### autoenv
source /usr/local/opt/autoenv/activate.sh

### java
alias java6="export JAVA_HOME=$(/usr/libexec/java_home -v1.6)"
alias java7="export JAVA_HOME=$(/usr/libexec/java_home -v1.7)"
alias java8="export JAVA_HOME=$(/usr/libexec/java_home -v1.8)"
alias java9="export JAVA_HOME=$(/usr/libexec/java_home -v9)"
java8

chmvn() {
  export M2_HOME=/Users/mvitz/Development/apps/apache-maven-$1
  export PATH="$M2_HOME/bin:$PATH"
}
alias mvn325='chmvn 3.2.5'
alias mvn333='chmvn 3.3.3'
mvn333

export ANT_HOME=/Users/mvitz/Development/apps/apache-ant-1.9.6
export PATH="$ANT_HOME/bin:$PATH"

export GRAILS_HOME=/Users/mvitz/Development/apps/grails-3.1.1
export PATH="$GRAILS_HOME/bin:$PATH"

export GRADLE_HOME=/Users/mvitz/Development/apps/gradle-2.11
export PATH="$GRADLE_HOME/bin:$PATH"

### postgres
alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'

### thefuckt
alias fuck='eval $(thefuck $(fc -ln -1)); history -r'

### activator
export ACTIVATOR_HOME="~/Development/apps/activator"
export PATH="$ACTIVATOR_HOME:$PATH"

### Mou
alias mou='/Applications/Mou.app/Contents/MacOS/Mou'

if brew command command-not-found-init > /dev/null; then
  eval "$(brew command-not-found-init)"
fi
export HOMEBREW_CASK_OPTS="$HOMEBREW_CASK_OPTS --caskroom=/opt/homebrew-cask/Caskroom"

# itermocil
complete -W "$(itermocil --list)" itermocil

# docker
alias dm-start='docker-machine start default && sleep 5 && eval $(docker-machine env default)'
alias dm-stop='docker-machine stop default && unset DOCKER_TLS_VERIFY DOCKER_HOST DOCKER_CERT_PATH DOCKER_MACHINE_NAME'
alias dm-status='docker-machine status default'
alias dm-restart='docker-machine-default-stop && docker-machine-default-start'

alias dps='docker ps'
alias drm-stopped='docker rm $(docker ps -a -q)'
alias drmi-dangling='docker rmi $(docker images -qf dangling=true)'
alias dvrm-dangling='docker volume rm $(docker volume ls -qf dangling=true)'

# misc
alias busy="cat /dev/urandom | hexdump -C | grep 'ca fe'"

# AWS
complete -C aws_completer aws
