# DEFAULTS
export EDITOR='vi'
export VISUAL='vi'
export PAGER='less'

# LESS
export LESS='-isMR --shift 5'

# HISTORY
#
# $ history
#  501 foo
#  502 bar
#  503 history
#
# !503           # history
# !-1            # history
# !!             # history
# !foo           # foo
# !?o?           # history
# ^foo^bar^      # bar
# !-3:s/foo/bar/ # bar
#
export HISTFILE=~/.zsh_history
export HISTSIZE=20000
export SAVEHIST=$HISTSIZE
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE

# PROGRAMMABLE FILE RENAMING
#
# zmv '(*).txt' '$1.html'
# zmv '(*)_(*)' '$1-$2'
# ...
#
autoload -U zmv


# EXTENDED GLOBBING AND EXPANSION
#
# ls dir/*<TAB> # expansion
# ls **/foo     # recursive
# ls [^ab]*     # negation
# ls (#a1)foo   # approimate matching
# ls foo/*(#q@) # qualifiers: @=symlink, .=file, /=directory, ==socket, p=named pipe, *=executable, r=readable, w=writable, x=executable, ...
#
setopt extended_glob

# SPELL CHECKING AND AUTO CORRECTION
setopt correct
#export SPROMPT="Correct '%R' to '%r'? (Yes, No, Abort, Edit) # TODO: colors
# To permanently disable auto correct for specific command use: alias foobar='nocorrect foobar'
