# custom .zshrc which contains basic stuff
#

# vi keybindings
bindkey -v

# enable color support
autoload -U colors && colors

# default editors
export EDITOR='vi'
export VISUAL='vi'
export PAGER='less'

# EXTENDED GLOBBING AND EXPANSION
#
# ls dir/*<TAB> # expansion
# ls **/foo     # recursive
# ls [^ab]*     # negation
# ls (#a1)foo   # approimate matching
# ls foo/*(#q@) # qualifiers: @=symlink, .=file, /=directory, ==socket, p=named pipe, *=executable, r=readable, w=writable, x=executable, ...
#setopt extended_glob

# SPELL CHECKING AND AUTO CORRECTION
#setopt correct
#export SPROMPT="Correct '%R' to '%r'? (Yes, No, Abort, Edit) # TODO: colors
# To permanently disable auto correct for specific command use: alias foobar='nocorrect foobar'

# including all specific scripts
dotfile_zsh_home=~/.dotfiles/zsh
for dotfile_zsh_script in $dotfile_zsh_home/*.zsh; do
  source $dotfile_zsh_script
done
unset dotfile_zsh_home
