# my custom .bashrc which should be sourced by ~/.bashrc
#

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# enable color support
if [ -r ~/.dircolors ]; then
  eval "$(dircolors -b ~/.dircolors)"
else
  eval "$(dircolors -b)"
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# some handy constants
export EDITOR='vi' # let vi be the default editor
export VISUAL='vi'
export PAGER='less'

# including all specific scripts
dotfile_bash_home=~/.dotfiles/bash
for dotfile_bash_script in $dotfile_bash_home/*.sh; do
  source $dotfile_bash_script
done
unset dotfile_bash_home
